name: Sync Dev with Main

on:
  push:
    branches:
      - main

jobs:
  sync-dev-with-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Merge changes from main into dev
        run: |
          git checkout dev
          git merge --ff-only main
          git push origin dev
